-- Follow-up hardening and administrator operations for the Test Portal.
-- Apply after 20260731_test_portal.sql.

ALTER TABLE public.test_admins
ADD COLUMN IF NOT EXISTS granted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS note TEXT NOT NULL DEFAULT '';

ALTER TABLE public.test_attempts
ADD COLUMN IF NOT EXISTS extension_minutes INTEGER NOT NULL DEFAULT 0
  CHECK (extension_minutes BETWEEN 0 AND 43200),
ADD COLUMN IF NOT EXISTS deadline_extended_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS deadline_extended_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.test_responses
ADD COLUMN IF NOT EXISTS graded_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS graded_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.test_admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (char_length(action) BETWEEN 1 AND 120),
  test_id UUID REFERENCES public.tests(id) ON DELETE SET NULL,
  attempt_id UUID REFERENCES public.test_attempts(id) ON DELETE SET NULL,
  question_id UUID REFERENCES public.test_questions(id) ON DELETE SET NULL,
  response_id UUID REFERENCES public.test_responses(id) ON DELETE SET NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_admin_audit_created
  ON public.test_admin_audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_test_admin_audit_test
  ON public.test_admin_audit_log(test_id, created_at DESC)
  WHERE test_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_test_admin_audit_attempt
  ON public.test_admin_audit_log(attempt_id, created_at DESC)
  WHERE attempt_id IS NOT NULL;
ALTER TABLE public.test_admin_audit_log ENABLE ROW LEVEL SECURITY;

-- A small database-backed limiter works consistently across serverless instances.
CREATE TABLE IF NOT EXISTS public.test_portal_rate_limits (
  bucket_key TEXT PRIMARY KEY,
  window_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  request_count INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_portal_rate_limits_updated
  ON public.test_portal_rate_limits(updated_at);

ALTER TABLE public.test_portal_rate_limits ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.consume_test_portal_rate_limit(
  p_bucket_key TEXT,
  p_limit INTEGER,
  p_window_seconds INTEGER
)
RETURNS TABLE(allowed BOOLEAN, remaining INTEGER, reset_at TIMESTAMPTZ)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := NOW();
  v_window_start TIMESTAMPTZ;
  v_request_count INTEGER;
  v_window INTERVAL;
BEGIN
  IF char_length(p_bucket_key) < 1 OR char_length(p_bucket_key) > 500 THEN
    RAISE EXCEPTION 'Invalid rate-limit bucket key';
  END IF;
  IF p_limit < 1 OR p_limit > 10000 OR p_window_seconds < 1 OR p_window_seconds > 86400 THEN
    RAISE EXCEPTION 'Invalid rate-limit configuration';
  END IF;

  v_window := make_interval(secs => p_window_seconds);

  INSERT INTO public.test_portal_rate_limits AS limits (
    bucket_key,
    window_start,
    request_count,
    updated_at
  )
  VALUES (p_bucket_key, v_now, 1, v_now)
  ON CONFLICT (bucket_key) DO UPDATE SET
    request_count = CASE
      WHEN limits.window_start <= v_now - v_window THEN 1
      ELSE limits.request_count + 1
    END,
    window_start = CASE
      WHEN limits.window_start <= v_now - v_window THEN v_now
      ELSE limits.window_start
    END,
    updated_at = v_now
  RETURNING limits.window_start, limits.request_count
  INTO v_window_start, v_request_count;

  allowed := v_request_count <= p_limit;
  remaining := GREATEST(0, p_limit - v_request_count);
  reset_at := v_window_start + v_window;
  RETURN NEXT;
END;
$$;

REVOKE ALL ON TABLE public.test_portal_rate_limits FROM anon, authenticated;
REVOKE ALL ON TABLE public.test_admin_audit_log FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.consume_test_portal_rate_limit(TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_test_portal_rate_limit(TEXT, INTEGER, INTEGER) TO service_role;

-- Keep response rows internally consistent even if a future server route makes
-- a mistake. This also prevents a response from referencing a problem on a
-- different test than its parent attempt.
CREATE OR REPLACE FUNCTION public.enforce_test_response_integrity()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  v_attempt_test_id UUID;
  v_question_test_id UUID;
  v_answer_type TEXT;
  v_max_points NUMERIC;
BEGIN
  SELECT test_id INTO v_attempt_test_id
  FROM public.test_attempts
  WHERE id = NEW.attempt_id;

  SELECT test_id, answer_type, points
  INTO v_question_test_id, v_answer_type, v_max_points
  FROM public.test_questions
  WHERE id = NEW.question_id;

  IF v_attempt_test_id IS NULL OR v_question_test_id IS NULL OR v_attempt_test_id <> v_question_test_id THEN
    RAISE EXCEPTION 'Response attempt and question must belong to the same test';
  END IF;
  IF NEW.points_awarded IS NOT NULL AND (NEW.points_awarded < 0 OR NEW.points_awarded > v_max_points) THEN
    RAISE EXCEPTION 'Response points are outside the question range';
  END IF;
  IF v_answer_type = 'numerical' AND (NEW.response_text IS NULL OR NEW.selected_choice IS NOT NULL OR NEW.file_path IS NOT NULL) THEN
    RAISE EXCEPTION 'Numerical response shape is invalid';
  ELSIF v_answer_type = 'multiple_choice' AND (NEW.selected_choice IS NULL OR NEW.response_text IS NOT NULL OR NEW.file_path IS NOT NULL) THEN
    RAISE EXCEPTION 'Multiple-choice response shape is invalid';
  ELSIF v_answer_type = 'file_upload' AND (
    NEW.file_path IS NULL OR NEW.file_name IS NULL OR NEW.file_mime_type IS NULL
    OR NEW.response_text IS NOT NULL OR NEW.selected_choice IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'File-upload response shape is invalid';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_test_response_integrity ON public.test_responses;
CREATE TRIGGER enforce_test_response_integrity
BEFORE INSERT OR UPDATE OF attempt_id, question_id, response_text, selected_choice, file_path, file_name, file_mime_type, points_awarded
ON public.test_responses
FOR EACH ROW EXECUTE FUNCTION public.enforce_test_response_integrity();

CREATE OR REPLACE FUNCTION public.enforce_test_security_event_owner()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.test_attempts
    WHERE id = NEW.attempt_id AND user_id = NEW.user_id
  ) THEN
    RAISE EXCEPTION 'Security event user must own the attempt';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_test_security_event_owner ON public.test_security_events;
CREATE TRIGGER enforce_test_security_event_owner
BEFORE INSERT OR UPDATE OF attempt_id, user_id ON public.test_security_events
FOR EACH ROW EXECUTE FUNCTION public.enforce_test_security_event_owner();

-- Revoke roles under an advisory transaction lock so two simultaneous requests
-- cannot race and remove every administrator.
CREATE OR REPLACE FUNCTION public.revoke_test_portal_admin(
  p_target_user_id UUID,
  p_actor_user_id UUID
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin_count INTEGER;
  v_deleted_count INTEGER;
BEGIN
  PERFORM pg_advisory_xact_lock(2053020260731);
  IF p_target_user_id = p_actor_user_id THEN
    RAISE EXCEPTION 'An administrator cannot revoke their own role';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.test_admins WHERE user_id = p_actor_user_id) THEN
    RAISE EXCEPTION 'The acting user is not a Test Portal administrator';
  END IF;
  SELECT COUNT(*) INTO v_admin_count FROM public.test_admins;
  IF v_admin_count <= 1 THEN
    RAISE EXCEPTION 'The final Test Portal administrator cannot be removed';
  END IF;
  DELETE FROM public.test_admins WHERE user_id = p_target_user_id;
  GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
  RETURN v_deleted_count = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.revoke_test_portal_admin(UUID, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_test_portal_admin(UUID, UUID) TO service_role;

-- Extend the event vocabulary without loosening the existing allowlist.
ALTER TABLE public.test_security_events
DROP CONSTRAINT IF EXISTS test_security_events_event_type_check;

ALTER TABLE public.test_security_events
ADD CONSTRAINT test_security_events_event_type_check CHECK (event_type IN (
  'attempt_started',
  'attempt_resumed',
  'visibility_hidden',
  'visibility_visible',
  'window_blurred',
  'window_focused',
  'fullscreen_entered',
  'fullscreen_exited',
  'fullscreen_unsupported',
  'copy_blocked',
  'paste_blocked',
  'session_unlocked_by_admin',
  'deadline_extended_by_admin',
  'grade_overridden_by_admin',
  'submitted',
  'timed_out'
));
